# Generated by Django 2.2 on 2020-01-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
